# Site settings
author: Drake Rentrop
title: Misadventures in Coding
header-img: img/home-bg.png
email: drakerentrop@gmail.com
copyright_name: Drake Rentrop
description: > # this means to ignore newlines until "baseurl:"
  A Programmer's Tale 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thadrake83

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
